DEMOPROJECT/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from DEMOPROJECT import views as DP_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #url(r'^$', DP_views.login_redirect, name='login_redirect'),
    path('',DP_views.login_redirect, name='login_redirect'),
    path('admin/', admin.site.urls),
    #Including Namespace
    path('accounts/',include(('accounts.urls','accounts'),namespace='accounts')),
    path('home/',include(('home.urls','home'),namespace='home')),
    #path('', include('DEMOAPP.urls')),
    path('', include('devonyes.urls')),
    path('',include('todoapp.urls')),
    #path('Portfolio/',include('examplepage.urls'))

    path('eshwar/',include('eshwar.urls'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/urls.py
from django.conf.urls import url
from django.urls import path,re_path
from django.contrib.auth.views import (
    LoginView ,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

# . means looks in folders for views file
from . import views
#for name space
#app_name= 'accounts'
#creating a list of URLS
urlpatterns = [
    path('',views.oldhome,name='accounts'),

    #rendering our login page than default page
    path('login/', LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/', LogoutView.as_view(template_name='accounts/logout.html'),name='logout'),
    path('register/',views.register, name='register'),
    path('profile/',views.view_profile, name='view_profile'),
    path('profile/<int:pk>/',views.view_profile, name='view_profile_with_prime_key'),
    path('profile/edit/',views.edit_profile, name='edit_profile'),
    path('change-password/',views.change_password, name='change_password'),
    #?
    path('profile/password/', views.change_password, name='change_password'),

    #password resetting
    path('reset-password/', PasswordResetView.as_view(template_name='accounts/reset_password.html',success_url='/accounts/reset-password/done',email_template_name='accounts/reset_password_email.html'), name='reset_password'),
    #to send email
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    #to check if mail is being sent to valid user (by sendind ID and Token)
    path('reset-password/confirm/<str:uidb64>/<str:token>/', PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html',success_url='/accounts/reset-password/complete/'), name='password_reset_confirm'),
    path('reset-password/complete/', PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete')

]

home/urls.py
from django.conf.urls import url
from django.urls import path
from home.views import HomeView
from . import views

urlpatterns =[
    path('', HomeView.as_view( ) ,name='accounty'),
    path('connect/<str:operation>/<int:pk>',  views.friendship,   name='friendship')
]

home/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    post = models.CharField(max_length=500)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

#friend list functionality
class Friend(models.Model):
    users = models.ManyToManyField(User)
    current_user = models.ForeignKey(User, related_name = 'other', on_delete=models.CASCADE, null=True)

    @classmethod
    def make_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(
            current_user = current_user
        )
        friend.users.add(new_friend)

    @classmethod
    def un_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(
            current_user=current_user
        )
        friend.users.remove(new_friend)

home/forms.py
from django import forms
from home.models import Post

class HomeForm(forms.ModelForm):
    post = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder':'write a post..'
        }
    )
    )

    class Meta:
        model = Post
        #use , for tuple unpacking
        fields = ('post',)

home/views.py
#creating class based views
from django.views.generic import TemplateView
from django.shortcuts import render, redirect
from home.forms import HomeForm
from home.models import Post, Friend
from django.urls import reverse
from django.contrib.auth.models import User


class HomeView(TemplateView):
    template_name ='home/home.html'
    #defining a form to render it in template
    def get(self, request):
        form = HomeForm()
        #retrieving info from DB
        posts = Post.objects.all().order_by('-created')

        #excluding the user who is requesting
        users = User.objects.exclude(id=request.user.id)

        friend = Friend.objects.get(current_user=request.user)
        friends = friend.users.all()

        args = {'form':form, 'posts':posts, 'users':users, 'friends': friends}
        return render(request, self.template_name, args )

    def post(self,request):
        form = HomeForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            text = form.cleaned_data['post']
            #make form empty again
            form = HomeForm()
            return redirect(reverse('home:accounty'))

        args =  {'form':form, 'text':text}
        return render(request, self.template_name, args)


def friendship(request, operation, pk):
    friend = User.objects.get(pk=pk)
    if operation=='add':
        Friend.make_friend(request.user,friend)
    elif operation=='remove':
        Friend.un_friend(request.user,friend)

    return redirect(reverse('home:accounty'))

home/templates/home/home.html
{% extends 'base.html' %}
{% block head %}
    <title>Home</title>
{% endblock %}


{% block body %}
<div class="container jumbotron">
    <div class="col-md-8">
        <h2>Home</h2>
    <form method="post">
        {% csrf_token %}
       {{ form.errors }}
        {{ form.post }}
        <br>
        <button class="submit">Submit</button>
        <!--<p>You just Posted:</p><h1> {{ text }}</h1>-->
        <br>
        <br>
        <h1>All Posts:</h1>
        {% for post in posts %}
        <ul><li><h1> {{ post.post }}</h1>
        <p>Posted by {{post.user.get_full_name}} at: {{post.created}}</p>
        </li></ul>
        {% endfor %}
        </form>
    </div>
    <div class="col-md-4">
        <h2>Other People</h2>
        {% for user in users %}
        <a href="{% url 'accounts:view_profile_with_prime_key' pk=user.pk%}"><h3>{{ user.username }}</h3></a>
        {% if user not in friends %}
        <a href="{% url 'home:friendship' operation='add' pk=user.pk %}">
        <button type="button" class="btn btn-success">Add Friend</button>
        </a>
        {% endif %}
        {% endfor %}

        <h2>Friends</h2>
        {% for friend in friends %}
        <a href="{% url 'accounts:view_profile_with_prime_key' pk=user.pk%}"><h3>{{ friend.username }}</h3></a>
        <a href="{% url 'home:friendship' operation='remove' pk=friend.pk%}">
        <button type="button" class="btn btn-warning">Remove Friend</button>
        </a>
        {% endfor %}
        </div>


</div>

{% endblock %}