DEMOPROJECT/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from DEMOPROJECT import views as DP_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #url(r'^$', DP_views.login_redirect, name='login_redirect'),
    path('',DP_views.login_redirect, name='login_redirect'),
    path('admin/', admin.site.urls),
    #Including Namespace
    path('accounts/',include(('accounts.urls','accounts'),namespace='accounts')),
    path('home/',include(('home.urls','home'),namespace='home')),
    #path('', include('DEMOAPP.urls')),
    path('', include('devonyes.urls')),
    path('',include('todoapp.urls')),
    #path('Portfolio/',include('examplepage.urls'))

    path('eshwar/',include('eshwar.urls'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/urls.py
from django.conf.urls import url
from django.urls import path,re_path
from django.contrib.auth.views import (
    LoginView ,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

# . means looks in folders for views file
from . import views
#for name space
#app_name= 'accounts'
#creating a list of URLS
urlpatterns = [
    path('',views.oldhome,name='accounts'),

    #rendering our login page than default page
    path('login/', LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/', LogoutView.as_view(template_name='accounts/logout.html'),name='logout'),
    path('register/',views.register, name='register'),
    path('profile/',views.view_profile, name='view_profile'),
    path('profile/<int:pk>/',views.view_profile, name='view_profile_with_prime_key'),
    path('profile/edit/',views.edit_profile, name='edit_profile'),
    path('change-password/',views.change_password, name='change_password'),
    #?
    path('profile/password/', views.change_password, name='change_password'),

    #password resetting
    path('reset-password/', PasswordResetView.as_view(template_name='accounts/reset_password.html',success_url='/accounts/reset-password/done',email_template_name='accounts/reset_password_email.html'), name='reset_password'),
    #to send email
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    #to check if mail is being sent to valid user (by sendind ID and Token)
    path('reset-password/confirm/<str:uidb64>/<str:token>/', PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html',success_url='/accounts/reset-password/complete/'), name='password_reset_confirm'),
    path('reset-password/complete/', PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete')

]

home/urls.py
from django.conf.urls import url
from django.urls import path
from home.views import HomeView
from . import views

urlpatterns =[
    path('', HomeView.as_view( ) ,name='accounty'),
    path('connect/<str:operation>/<int:pk>',  views.friendship,   name='friendship')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
#signals allow certain senders to notify a set of receivers that some action has taken place
from django.db.models.signals import post_save

#creating custom objects
class UserProfileManager(models.Manager):
    def get_queryset(self):
        return super(UserProfileManager,self).get_queryset().filter(city='Denton')

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    description = models.CharField(max_length=100, default='')
    city= models.CharField(max_length=100, default='')
    website = models.URLField(default='')
    phone = models.IntegerField(default=0)
    image = models.ImageField(upload_to='profile_image',blank=True)
    #to display names in UserProfile Module
    def __str__(self):
        return self.user.username

    #creating an object named denton
    #in shell use this cmd UserProfile.denton.all()
    denton = UserProfileManager()

#receiver function to which signal is sent
def create_profile(sender,**kwargs):
    if kwargs['created']:
        user_profile= UserProfile.objects.create(user = kwargs['instance'])




#to receive a signal, registering receiver(create_profile) function using connect() method
#fn() called when signal is sent
post_save.connect(create_profile, sender = User)

accounts/forms.py
from django import forms
#from django.db import models
#importing User model to replicate it
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

#adding our fields to the already existing UserCreationForm
class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    #telling form some information about itself
    class Meta:
        model=User
        fields ={
            'username','first_name','last_name','email','password1','password2'
        }
    #saving into DB
    def save(self, commit=True):
        user = super(RegistrationForm,self).save(commit=False)
        #cleaned_data is to check the input is clean
        user.first_name= self.cleaned_data['first_name']
        user.last_name=self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

#custom edit profile form
class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        #fields, exclude are variables used to include on exclude in the template
        fields = {
            'email',
            'first_name',
            'last_name',
            'password'
        }

accounts/views.py
from django.shortcuts import render, HttpResponse,redirect
#import userCreation,EditProfile form
from django.contrib.auth.forms import UserCreationForm
#import userChangeForm for editing profile
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
#for profile View
from django.contrib.auth.models import User
#import userCreation form
from accounts.forms import (
    RegistrationForm,
    EditProfileForm
)
#to make sure session is still continuing
from django.contrib.auth import update_session_auth_hash
from django.urls import reverse
#editing views functionality using django
#from django.contrib.auth.decorators import login_required


# Create your views here.

def oldhome(request):
    #creating arguments to be called in templates
    numbers = [1,2,3,4,5]
    args = {'numbers' : numbers}
    return render(request,'accounts/oldhome.html',args)

def register(request):
    #check if form data is posted
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/accounts/profile/')
        else:
            form = RegistrationForm()
            args = {'form': form}
            #check if User is present in DB
            #give a return statement here! Saying Data invalid Enter Valid Details
            return render(request, 'accounts/register.html', args)
    #if user enters data first time
    else:
        form = RegistrationForm()
        args = {'form':form}
        return render(request,'accounts/register.html',args)


def view_profile(request, pk=None):
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
    args = {'user': user}
    return render(request,'accounts/profile.html',args)


def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance = request.user)
        if form.is_valid():
            form.save()
            #go back to the same old url(looks for url defiled with name='view_profile'
            return redirect(reverse('accounts:view_profile'))
        else:
            form = EditProfileForm(instance=request.user)
            args = {'form': form}
            return render(request, 'accounts/edit_profile.html', args)
    else:
        form =EditProfileForm(instance=request.user)
        args = {'form':form}
        return render(request,'accounts/edit_profile.html',args)


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data= request.POST, user = request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect(reverse('view_profile'))
        else:
            form = PasswordChangeForm(user = request.user)
            args = {'form': form}
            return render(request, 'accounts/change_password.html',args)
    else:
        form = PasswordChangeForm(user = request.user)
        args ={ 'form':form}
        return render(request, 'accounts/change_password.html',args)

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block head %}

{% load static %}
<link rel="stylesheet" href="{% static 'accounts/style1.css' %}">

<title>Profile</title>
{% endblock %}


{% block body %}
<div class="container jumbotron">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}

{% block head %}

{% load static %}
<link rel="stylesheet" href="{% static 'accounts/style1.css' %}">

<title>Profile</title>
{% endblock %}


{% block body %}
<div class="container jumbotron">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}


{% block head %}
<!-- adding stylesheet by loading static files -->
{% load static %}
<link rel="stylesheet" href="{% static 'accounts/style1.css' %}">
<title>Login</title>
{% endblock %}


{% block body %}
<div class="container jumbotron" >
    <h1>Welcome</h1>
    <p>Login Here!!</p>
    <form method="post">
        <!-- To check the the values entered are secure -->
        {% csrf_token %}
        <!-- form as paragraph(login and password) -->
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Login</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}


<head>
    {% block head %}
    <meta charset="UTF-8">
    <title>logout</title>
    {% endblock %}
</head>
<body>
    {% block body%}
    <div class="container jumbotron">
        <p> You have logged out!!</p>
    </div>
    {% endblock %}

</body>
</html>

accounts/templates/accounts/oldhome.html
<!--Registering the base.html file-->
{% extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- overwriting content in base.html file-->
    {% block head %}
    <meta charset="UTF-8">
    <title>Home</title>
    {% endblock %}
</head>
<body>
    {% block body %}
    <h1>OldHome</h1>
    {% endblock %}

</body>
</html>

accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}


{% block head %}
<!-- adding stylesheet by loading static files -->
{% load static %}
<link rel="stylesheet" href="{% static 'accounts/style1.css' %}">
<title>Login</title>
{% endblock %}


{% block body %}
<div class="container jumbotron" >
    <h1>Password reset complete</h1>
    <p>Your password has been set. You may go ahead and log in now.</p>
    <button class="btn btn-success"><a href="{% url 'accounts:login' %}">Login</a></button>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}


{% block head %}
<!-- adding stylesheet by loading static files -->
{% load static %}
<link rel="stylesheet" href="{% static 'accounts/style1.css' %}">
<title>Reset Password</title>
{% endblock %}


{% block body %}
<div class="container jumbotron" >
    <h1>Welcome</h1>
    <p>Reset Password!!</p>
    <form method="post">
        <!-- To check the the values entered are secure -->
        {% csrf_token %}
        <!-- form as paragraph(login and password) -->
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Reset Password</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}


{% block head %}
<!-- adding stylesheet by loading static files -->
{% load static %}
<link rel="stylesheet" href="{% static 'accounts/style1.css' %}">
<title>Password Reset</title>
{% endblock %}


{% block body %}
<div class="container jumbotron" >
    <h1>Welcome</h1>
    <p>A Mail has been sent to your account!! Please change your Password there!!</p>

</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block head %}

{% load static %}
<link rel="stylesheet" href="{% static 'accounts/style1.css' %}">

<title>Profile</title>
{% endblock %}


{% block body %}
<div class="container jumbotron">
    <h1>Profile</h1>
    <span>Hello , </span>{{ user.first_name }} {{ user.last_name }}
    <br>
    <span>Your Email: {{ user.email }}</span>
    <p>Description: {{user.userprofile.description}}</p>
    {% if user.userprofile.image %}
    <img src={{ user.userprofile.image.url }} width="240">
    {% endif %}
</div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% block head %}

{% load static %}
<link rel="stylesheet" href="{% static 'accounts/style1.css' %}">
    <title>Register</title>

{% endblock %}

{% block body %}

<div class="container jumbotron">
    <h1>Register Here</h1>
    <!-- Form order is changing upon reloading
    #goto forms.py and check fields variable-->
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }} 
        <button type="submit" class="btn btn-success">Register</button>
    </form>

</div>

{% endblock %}

accounts/templates/accounts/reset_password.html
{% extends 'base.html' %}


{% block head %}
<!-- adding stylesheet by loading static files -->
{% load static %}
<link rel="stylesheet" href="{% static 'accounts/style1.css' %}">
<title>Login</title>
{% endblock %}


{% block body %}
<div class="container jumbotron" >
    <h1>Welcome </h1>
    <p>Reset Password!!</p>
    <form method="post">
        <!-- To check the the values entered are secure -->
        {% csrf_token %}
        <!-- form as paragraph(login and password) -->
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Reset Password</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/reset_password_email.html
	{% load i18n %}{% autoescape off %}
	{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

	{% trans "Please go to the following page and choose a new password:" %}
	{% block reset_link %}
	{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
	{% endblock %}
    	{% trans 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

	{% trans "Thanks for using our site!" %}

	{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

    {% endautoescape %}