DEMOPROJECT/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from DEMOPROJECT import views as DP_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #url(r'^$', DP_views.login_redirect, name='login_redirect'),
    path('',DP_views.login_redirect, name='login_redirect'),
    path('admin/', admin.site.urls),
    #Including Namespace
    path('accounts/',include(('accounts.urls','accounts'),namespace='accounts')),
    path('home/',include(('home.urls','home'),namespace='home')),
    #path('', include('DEMOAPP.urls')),
    path('', include('devonyes.urls')),
    path('',include('todoapp.urls')),
    #path('Portfolio/',include('examplepage.urls'))

    path('eshwar/',include('eshwar.urls'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/urls.py
from django.conf.urls import url
from django.urls import path,re_path
from django.contrib.auth.views import (
    LoginView ,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

# . means looks in folders for views file
from . import views
#for name space
#app_name= 'accounts'
#creating a list of URLS
urlpatterns = [
    path('',views.oldhome,name='accounts'),

    #rendering our login page than default page
    path('login/', LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/', LogoutView.as_view(template_name='accounts/logout.html'),name='logout'),
    path('register/',views.register, name='register'),
    path('profile/',views.view_profile, name='view_profile'),
    path('profile/<int:pk>/',views.view_profile, name='view_profile_with_prime_key'),
    path('profile/edit/',views.edit_profile, name='edit_profile'),
    path('change-password/',views.change_password, name='change_password'),
    #?
    path('profile/password/', views.change_password, name='change_password'),

    #password resetting
    path('reset-password/', PasswordResetView.as_view(template_name='accounts/reset_password.html',success_url='/accounts/reset-password/done',email_template_name='accounts/reset_password_email.html'), name='reset_password'),
    #to send email
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    #to check if mail is being sent to valid user (by sendind ID and Token)
    path('reset-password/confirm/<str:uidb64>/<str:token>/', PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html',success_url='/accounts/reset-password/complete/'), name='password_reset_confirm'),
    path('reset-password/complete/', PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete')

]

home/urls.py
from django.conf.urls import url
from django.urls import path
from home.views import HomeView
from . import views

urlpatterns =[
    path('', HomeView.as_view( ) ,name='accounty'),
    path('connect/<str:operation>/<int:pk>',  views.friendship,   name='friendship')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
#signals allow certain senders to notify a set of receivers that some action has taken place
from django.db.models.signals import post_save

#creating custom objects
class UserProfileManager(models.Manager):
    def get_queryset(self):
        return super(UserProfileManager,self).get_queryset().filter(city='Denton')

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    description = models.CharField(max_length=100, default='')
    city= models.CharField(max_length=100, default='')
    website = models.URLField(default='')
    phone = models.IntegerField(default=0)
    image = models.ImageField(upload_to='profile_image',blank=True)
    #to display names in UserProfile Module
    def __str__(self):
        return self.user.username

    #creating an object named denton
    #in shell use this cmd UserProfile.denton.all()
    denton = UserProfileManager()

#receiver function to which signal is sent
def create_profile(sender,**kwargs):
    if kwargs['created']:
        user_profile= UserProfile.objects.create(user = kwargs['instance'])




#to receive a signal, registering receiver(create_profile) function using connect() method
#fn() called when signal is sent
post_save.connect(create_profile, sender = User)

accounts/forms.py
from django import forms
#from django.db import models
#importing User model to replicate it
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

#adding our fields to the already existing UserCreationForm
class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    #telling form some information about itself
    class Meta:
        model=User
        fields ={
            'username','first_name','last_name','email','password1','password2'
        }
    #saving into DB
    def save(self, commit=True):
        user = super(RegistrationForm,self).save(commit=False)
        #cleaned_data is to check the input is clean
        user.first_name= self.cleaned_data['first_name']
        user.last_name=self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

#custom edit profile form
class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        #fields, exclude are variables used to include on exclude in the template
        fields = {
            'email',
            'first_name',
            'last_name',
            'password'
        }

accounts/views.py
from django.shortcuts import render, HttpResponse,redirect
#import userCreation,EditProfile form
from django.contrib.auth.forms import UserCreationForm
#import userChangeForm for editing profile
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
#for profile View
from django.contrib.auth.models import User
#import userCreation form
from accounts.forms import (
    RegistrationForm,
    EditProfileForm
)
#to make sure session is still continuing
from django.contrib.auth import update_session_auth_hash
from django.urls import reverse
#editing views functionality using django
#from django.contrib.auth.decorators import login_required


# Create your views here.

def oldhome(request):
    #creating arguments to be called in templates
    numbers = [1,2,3,4,5]
    args = {'numbers' : numbers}
    return render(request,'accounts/oldhome.html',args)

def register(request):
    #check if form data is posted
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/accounts/profile/')
        else:
            form = RegistrationForm()
            args = {'form': form}
            #check if User is present in DB
            #give a return statement here! Saying Data invalid Enter Valid Details
            return render(request, 'accounts/register.html', args)
    #if user enters data first time
    else:
        form = RegistrationForm()
        args = {'form':form}
        return render(request,'accounts/register.html',args)


def view_profile(request, pk=None):
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
    args = {'user': user}
    return render(request,'accounts/profile.html',args)


def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance = request.user)
        if form.is_valid():
            form.save()
            #go back to the same old url(looks for url defiled with name='view_profile'
            return redirect(reverse('accounts:view_profile'))
        else:
            form = EditProfileForm(instance=request.user)
            args = {'form': form}
            return render(request, 'accounts/edit_profile.html', args)
    else:
        form =EditProfileForm(instance=request.user)
        args = {'form':form}
        return render(request,'accounts/edit_profile.html',args)


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data= request.POST, user = request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect(reverse('view_profile'))
        else:
            form = PasswordChangeForm(user = request.user)
            args = {'form': form}
            return render(request, 'accounts/change_password.html',args)
    else:
        form = PasswordChangeForm(user = request.user)
        args ={ 'form':form}
        return render(request, 'accounts/change_password.html',args)

accounts/templates/base.html
<!-- Base file to be included in all the template files -->

<!DOCTYPE html>
<html lang="en">
<head>
    <!--<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

    <!-- adding stylesheet by loading static files -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'accounts/style1.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- creating ginger tooth head block-->
    {% block head %}
    <title>Base</title>
    {% endblock %}
</head>
<body>
<br>
    <div class="container">

      <!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header ">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
              <!--bringing from HomeApp-->
            <a class="navbar-brand" href="{% url 'home:accounty' %}">Accounty</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
             {% if user.is_authenticated %}
              <ul class="nav navbar-nav">
                    <!--Removing Hardcoded URLS and using ginder coding-->
                  <li><a href="{% url 'accounts:view_profile' %}">Profile</a></li>
                  <li><a href="{% url 'accounts:change_password' %}">Change Password</a></li>
                  <li><a href="{% url 'accounts:edit_profile' %}">Edit Profile</a></li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                  <li><a href="/accounts/logout">Logout</a></li>
              </ul>


             {% else %}
              <ul class="nav navbar-nav navbar-right">
                  <li><a href="/accounts/reset-password/">Reset Password</a></li>
                  <li><a href="/accounts/login/">Login</a></li>
                  <li><a href="/accounts/register/">Register</a></li>
            </ul>
              {% endif %}
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>


  </div>
</nav>
        <br>
    </div><!-- container -->

    {% block body %}
    <h1>Base</h1>
    {% endblock%}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

</body>

</html>